version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootloader
    versions:
    - 0.10.0
    - 0.9.11
    - 0.9.12
    - 0.9.14
    - 0.9.16
